### ISSUE TITLE
Form component

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-alpaca-components#111]
Find out if we really need it.

Might be useful for:
- complex forms with lot's of inputs, to easier, keep styling in sync (i.e. margin below each filed or fields group)
- to change "flow" from horizontal (label on top of input) to vertical (label in same line as input)

**Comment by kjugi** [comment]
We don't have to add new modifiers in i.e. `input` element and don't mess up in this code but we can add a class with an element in our `form`. 

If it's the same as the first point, ignore this comment.

In addition to this, it will be helpful in customer projects b/c they may want some other form design and it will be easier to overwrite form and adjust styles to project than adding other custom things.
But it can be same as the second point but in other words.

We can spare a lot of code creating a good `form` module. In views, it's good to keep the only necessary thing. If we will delete it, we have a lot of `input`'s imports b/c we are creating a form. If we will rebuild actual form to adding as much as we want fields and then we have in our view only 1 render with `form` and the rest of code in view config.

**Comment by Januszpl** [comment]
Flow of label in inputs should be in input element varation I guess (unless we have there only a input without label?) 

Looking at ... https://getuikit.com/v2/docs/form.html

Anyway I think it depend on the implementation. So instead of writing someone could create some example of component and examples of different implementation to see is it good or not.

I would try to first buil forms on form elements and then we will see what kind of form component we need to build

**Comment by anqaka** [comment]
I've made accessibility update for radio input, details here: issue: #125 , PR: #126

**Comment by Igloczek** [comment]
Form removed.
